services:
  app:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app:/app/app
    networks:
      - existing_db_network

networks:
  existing_db_network:
    external: true
    name: task_app_db_default