"""make_task_user_id_nullable

Revision ID: 27db0ef22d45
Revises: 54d9a4579f63
Create Date: 2026-08-29 08:25:18.480370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27db0ef22d45"
down_revision: str | Sequence[str] | None = "54d9a4579f63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
