"""add_user_id_to_tags

Revision ID: 54d9a4579f63
Revises: b3333b6ab90f
Create Date: 2026-08-28 09:07:17.121743

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54d9a4579f63"
down_revision: str | Sequence[str] | None = "b3333b6ab90f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tags", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("tags_user_id_fkey"), "tags", type_="foreignkey")
    op.create_foreign_key(
        None, "tags", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.create_foreign_key(
        op.f("tags_user_id_fkey"), "tags", "users", ["user_id"], ["id"]
    )
    op.alter_column("tags", "user_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
