"""fix_tag_description_unique_and_nullables

Revision ID: 80fabe0f3a64
Revises: 27db0ef22d45
Create Date: 2026-08-29 08:45:54.816328

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80fabe0f3a64"
down_revision: str | Sequence[str] | None = "27db0ef22d45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tags_description_key"), "tags", type_="unique")
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    op.create_unique_constraint(
        op.f("tags_description_key"),
        "tags",
        ["description"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
