"""add_user_id_to_tags

Revision ID: b3333b6ab90f
Revises: ac9a5144a3cd
Create Date: 2026-08-28 09:01:58.551642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3333b6ab90f'
down_revision: Union[str, Sequence[str], None] = 'ac9a5144a3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    op.drop_column('tags', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###
